version: "3.8"

services:
  evolution-manager:
    image: evoapicloud/evolution-manager:latest
    container_name: evolution-manager
    restart: unless-stopped
    ports:
      - "8081:3000"
    environment:
      - NEXT_PUBLIC_EVOLUTION_API_URL=http://18.207.71.231:8080
