version: "3.8"

services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    ports:
      - "45876:8090"
    volumes:
      - ./data:/beszel_data
    environment:
      - DISABLE_PASSWORD_AUTH=false
